# Generated by Django 5.0.3 on 2024-04-05 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessond_drf', '0004_newsmodelfirst_newsmodelsecond_newsmodelthird'),
    ]

    operations = [
        migrations.CreateModel(
            name='InternetShop',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('add_date', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('category', models.CharField(max_length=100)),
                ('sum_product', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='NewsModel',
        ),
        migrations.DeleteModel(
            name='NewsModelFirst',
        ),
        migrations.DeleteModel(
            name='NewsModelSecond',
        ),
        migrations.DeleteModel(
            name='NewsModelThird',
        ),
    ]
